dependencies:
- name: demo
  repository: http://chartmuseum.jx.eks.xuzhong11.test.thunderhead.io
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: golang-http
  repository: http://chartmuseum.jx.eks.xuzhong11.test.thunderhead.io
  version: 0.0.3
- name: nodejx
  repository: http://chartmuseum.jx.eks.xuzhong11.test.thunderhead.io
  version: 0.0.13
